/*
 * generated by Xtext
 */
package org.slf;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class IotRuntimeModule extends org.slf.AbstractIotRuntimeModule {

}
