/*
 * generated by Xtext
 */
package org.slf;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class IotStandaloneSetup extends IotStandaloneSetupGenerated{

	public static void doSetup() {
		new IotStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

