/**
 * generated by Xtext
 */
package org.slf.validation;

import org.slf.validation.AbstractIotValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class IotValidator extends AbstractIotValidator {
}
